import { copyFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import builtins from 'builtin-modules'
import esbuild from 'esbuild'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Repository: https://github.com/doocs/md
*/`

const prod = process.argv[2] === 'production'

// 开发模式：输出到 Obsidian 测试仓库的插件目录
const vaultPath = process.env.OBSIDIAN_VAULT_PATH
const pluginDir = vaultPath
  ? path.join(vaultPath, '.obsidian', 'plugins', 'wechat-publisher')
  : null

// Plugin to handle Vite-style ?raw imports (used by @md/shared)
const rawImportPlugin = {
  name: 'raw-import',
  setup(build) {
    build.onResolve({ filter: /\?raw$/ }, (args) => {
      const resolved = path.resolve(args.resolveDir, args.path.replace(/\?raw$/, ''))
      return { path: resolved }
    })
  },
}

// 开发模式下构建完成后自动复制到测试仓库
const deployPlugin = {
  name: 'deploy-to-vault',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0 || !pluginDir)
        return
      await mkdir(pluginDir, { recursive: true })
      const src = path.dirname(new URL(import.meta.url).pathname)
      await copyFile(path.join(src, 'manifest.json'), path.join(pluginDir, 'manifest.json'))
      await copyFile(path.join(src, 'styles', 'styles.css'), path.join(pluginDir, 'styles.css'))
      // main.js 由 esbuild 直接输出到 pluginDir
      console.log(`Deployed to ${pluginDir}`)
    })
  },
}

const outfile = prod
  ? 'dist/main.js'
  : pluginDir
    ? path.join(pluginDir, 'main.js')
    : 'main.js'

const plugins = [rawImportPlugin]
if (!prod && pluginDir) {
  plugins.push(deployPlugin)
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile,
  minify: prod,
  plugins,
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  loader: {
    '.css': 'text',
    '.txt': 'text',
  },
})

if (prod) {
  await context.rebuild()
  await context.dispose()

  await mkdir('dist', { recursive: true })
  await copyFile('manifest.json', 'dist/manifest.json')
  await copyFile('styles/styles.css', 'dist/styles.css')

  console.log('Build complete!')
}
else {
  await context.watch()
  console.log(`Watching for changes...${pluginDir ? ` (deploying to ${pluginDir})` : ''}`)
}
